{% set version = "3.11.7" %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-bom/cyclonedx_bom-{{ version }}.tar.gz
    sha256: 656a6df47511abff82c159dfa947a6f881ec971d1b9861ec14802bc50bc29e05
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3b005ad5ed32e42feac14471c5884f33a74ea1ab81b01b3403a6de1b0d697ac3

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-bom = cyclonedx_py.client:main_deprecated
    - cyclonedx-py = cyclonedx_py.client:main
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - {{ PYTHON }} -c "import site, pathlib; sp = pathlib.Path(site.getsitepackages()[0]); [(sp / p).unlink() for p in ['LICENSE', 'NOTICE']]"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - chardet >=5.0.0,<6.0.0
    - cyclonedx-python-lib >=2.0.0,<4.0.0
    - importlib-metadata >=3.4
    - packageurl-python >=0.9
    - pip-requirements-parser >=32.0.0,<33.0.0
    - python >=3.6
    - setuptools >=47.0.0
    - toml >=0.10.0,<0.11.0

test:
  {% set cov_fail_under = 65 %}
  {% set test_skips = "not test_simple" %}
  source_files:
    - src/tests
  requires:
    - ddt
    - pip
    - pytest-cov
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-bom --help
    - cyclonedx-py --help
    - cd src && pytest -vv --color=yes --tb=long --cov=cyclonedx_py --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "{{ test_skips }}" --cov-fail-under={{ cov_fail_under }}

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
