{% set version = "5.1.2" %}
{% set python_min = python_min | default("3.9") %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/c/cyclonedx-bom/cyclonedx_bom-{{ version }}.tar.gz
    sha256: 69cbabd884d1ca0c500d0307c42bdd93b0e42ee302a316fc5e45b5609bd898c7
  # pypi sdist does not include all test data
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: dc540d781728c24f83a840586505aa304597e314034c7902a9faf3854b403f94

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-py = cyclonedx_py._internal.cli:run
  script:
    - cd src && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - {{ PYTHON }} -c "import site, pathlib; sp = pathlib.Path(site.getsitepackages()[0]); assert not all((sp / p).exists() for p in ['LICENSE', 'NOTICE']);"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - chardet >=5.1.0,<6.0.0
    - cyclonedx-python-lib >=8.0,<9.0
    - cyclonedx-python-lib-with-validation
    - packageurl-python >=0.11,<2
    - packaging >=22.0.0,<25.0.0
    - pip-requirements-parser >=32.0.0,<33.0.0
    - python >={{ python_min }}
    - tomli >=2.0.1,<3.0.0

test:
  source_files:
    - src/tests
    - src/pyproject.toml
  requires:
    - coverage
    - ddt
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-py --help
    - python -c "__import__('pathlib').Path('src/tests/integration/test_cli_environment.py').unlink()"
    - coverage run --source cyclonedx_py --branch -m pytest src/tests -vv --color=yes --tb=long -k "not ( simple or data_file_filter or data_os_filter )"
    - coverage report --show-missing --skip-covered --fail-under=74

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
