{% set version = "4.5.0" %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-bom/cyclonedx_bom-{{ version }}.tar.gz
    sha256: 09a9a6c3b86e1a143f2d89a4955a8e303abed7106adc4f5f0207ae0e3416ff86
  # pypi sdist does not include all test data
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: eda02415b9df1931b0eca179ecbe23396b3d6e8a064f05d0240845b42b02a888

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-py = cyclonedx_py._internal.cli:run
  script:
    - cd src && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - {{ PYTHON }} -c "import site, pathlib; sp = pathlib.Path(site.getsitepackages()[0]); assert not all((sp / p).exists() for p in ['LICENSE', 'NOTICE']);"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - chardet >=5.1.0,<6.0.0
    - cyclonedx-python-lib >=7.3.0,<8.0.0,!=7.3.1
    - cyclonedx-python-lib-with-validation
    - packageurl-python >=0.11,<2
    - packaging >=22.0.0,<25.0.0
    - pip-requirements-parser >=32.0.0,<33.0.0
    - python >=3.8
    - tomli >=2.0.1,<3.0.0

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - ddt
    - pip
    - pytest
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-py --help
    - python -c "__import__('pathlib').Path('src/tests/integration/test_cli_environment.py').unlink()"
    - coverage run --source cyclonedx_py --branch -m pytest src/tests -vv --color=yes --tb=long -k "not ( simple or data_file_filter or data_os_filter )"
    - coverage report --show-missing --skip-covered --fail-under=76

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
