# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "7.5.0"
  python_check_max: "3.14"

package:
  name: cyclonedx-bom
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/cyclonedx-bom/cyclonedx_bom-${{ version }}.tar.gz
    sha256: 396cc8c9cb7533d25a21f930b45d2699a1839e3ba2be9ba88f8bd61c566b51dc
    target_directory: dist
  # pypi sdist does not include all test data
  - url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v${{ version }}.tar.gz
    sha256: a517435b267429c65217e03c3be7b4d9b5a8ea9d76105bfaa3f12a2162a54a35
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    file: build-cyclonedx-bom.py
    interpreter: python
  python:
    entry_points:
      - cyclonedx-py = cyclonedx_py._internal.cli:run

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - chardet >=5.1.0,!=6.*,<8
    - cyclonedx-python-lib >=8.0.0,<12.0.0
    - cyclonedx-python-lib-with-validation
    - packageurl-python >=0.11.0,<2.0.0
    - packaging >=22.0.0,<27.0.0
    - pip-requirements-parser >=32.0.0,<33.0.0
    - python >=${{ python_min }}

tests:
  - package_contents:
      strict: true
      files:
        - etc/conda/test-files/cyclonedx-bom/**
      site_packages:
        - cyclonedx_py/**
        - cyclonedx_bom-${{ version }}.dist-info/**
  - python:
      imports: cyclonedx_py
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      recipe:
        - run_test.py
      source:
        - src/tests/
        - src/pyproject.toml
    requirements:
      run:
        - coverage
        - ddt
        - pytest
        - python ${{ python_min }}.*
    script:
      - cyclonedx-py --help
      - python run_test.py

about:
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE
  homepage: https://pypi.org/project/cyclonedx-bom
  repository: https://github.com/CycloneDX/cyclonedx-python

extra:
  recipe-maintainers:
    - bollwyvl
