# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "5.2.0"

package:
  name: cyclonedx-bom
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/cyclonedx-bom/cyclonedx_bom-${{ version }}.tar.gz
    sha256: 4a4ac184dc050a34e90cc0826cebe7952b834e4ff252abbaf5a40de9d67bc310
    target_directory: dist
  # pypi sdist does not include all test data
  - url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 891785b56075826a4a7050a3b75fdaa63a09db5a606ce18be1c14ccad662e9fe
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd src && ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - ${{ PYTHON }} -c "import site, pathlib; sp = pathlib.Path(site.getsitepackages()[0]); assert not all((sp / p).exists() for p in ['LICENSE', 'NOTICE']);"
  python:
    entry_points:
      - cyclonedx-py = cyclonedx_py._internal.cli:run

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - chardet >=5.1.0,<6.0.0
    - cyclonedx-python-lib >=8.0,<9.0
    - cyclonedx-python-lib-with-validation
    - packageurl-python >=0.11,<2
    - packaging >=22.0.0,<25.0.0
    - pip-requirements-parser >=32.0.0,<33.0.0
    - python >=${{ python_min }}
    - tomli >=2.0.1,<3.0.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      pip_check: true
      imports:
        - cyclonedx_py
  - files:
      source:
        - src/tests/
        - src/pyproject.toml
    requirements:
      run:
        - coverage
        - ddt
        - pytest
        - python ${{ python_min }}.*
    script:
      - cyclonedx-py --help
      - python -c "__import__('pathlib').Path('src/tests/integration/test_cli_environment.py').unlink()"
      - coverage run --source cyclonedx_py --branch -m pytest src/tests -vv --color=yes --tb=long -k "not ( simple or data_file_filter or data_os_filter )"
      - coverage report --show-missing --skip-covered --fail-under=74

about:
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE
  homepage: https://github.com/CycloneDX/cyclonedx-python

extra:
  recipe-maintainers:
    - bollwyvl
