# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.0.0"

package:
  name: cyclonedx-bom
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/cyclonedx-bom/cyclonedx_bom-${{ version }}.tar.gz
    sha256: 78f05ad294552aa6f11867d243649a8869f7fd463f87cd61334da813fa7ef06e
    target_directory: dist
  # pypi sdist does not include all test data
  - url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v${{ version }}.tar.gz
    sha256: cceb0f45fc9669074f811817b59c0029f5f359136176c079260e6861bb8f339f
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd src && ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - ${{ PYTHON }} -c "import site, pathlib; sp = pathlib.Path(site.getsitepackages()[0]); assert all(not (sp / p).exists() for p in ['LICENSE', 'NOTICE']);"
  python:
    entry_points:
      - cyclonedx-py = cyclonedx_py._internal.cli:run

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - chardet >=5.1.0,<6.0.0
    - cyclonedx-python-lib >=8.0,<11.0
    - cyclonedx-python-lib-with-validation
    - packageurl-python >=0.11,<2
    - packaging >=22.0.0,<26.0.0
    - pip-requirements-parser >=32.0.0,<33.0.0
    - python >=${{ python_min }}
    - tomli >=2.0.1,<3.0.0

tests:
  - python:
      imports: cyclonedx_py
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      recipe:
        - run_test.py
      source:
        - src/tests/
        - src/pyproject.toml
    requirements:
      run:
        - coverage
        - ddt
        - pytest
        - python ${{ python_min }}.*
    script:
      - cyclonedx-py --help
      - python run_test.py

about:
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE
  homepage: https://github.com/CycloneDX/cyclonedx-python

extra:
  recipe-maintainers:
    - bollwyvl
