# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "7.2.0"

package:
  name: cyclonedx-bom
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/cyclonedx-bom/cyclonedx_bom-${{ version }}.tar.gz
    sha256: 5cf3a519514fc356fce28ec1b744f24b965efe5923d592ab393efd1a646a51d4
    target_directory: dist
  # pypi sdist does not include all test data
  - url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 677a2e4c3a60e72c7ca5202c3575adb2101a971cbedd287ac87331d1158ad3f0
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    file: build-cyclonedx-bom.py
    interpreter: python
  python:
    entry_points:
      - cyclonedx-py = cyclonedx_py._internal.cli:run

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - chardet >=5.1.0,<6.0.0
    - cyclonedx-python-lib >=8.0,<12.0
    - cyclonedx-python-lib-with-validation
    - packageurl-python >=0.11,<2
    - packaging >=22.0.0,<26.0.0
    - pip-requirements-parser >=32.0.0,<33.0.0
    - python >=${{ python_min }}
    - tomli >=2.0.1,<3.0.0

tests:
  - python:
      imports: cyclonedx_py
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.14.*
  - files:
      recipe:
        - run_test.py
      source:
        - src/tests/
        - src/pyproject.toml
    requirements:
      run:
        - coverage
        - ddt
        - pytest
        - python ${{ python_min }}.*
    script:
      - cyclonedx-py --help
      - python run_test.py

about:
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE
  homepage: https://github.com/CycloneDX/cyclonedx-python

extra:
  recipe-maintainers:
    - bollwyvl
